### ISSUE TITLE
fps 

### ISSUE THREAD

**Issue by jakbes** [demitriusdemarcus/X0N3-source-leak-fix#1]
is it normal to get **LOCKED** 80 fps instead of 300?

**Comment by demitriusdemarcus** [comment]
> is it normal to get **LOCKED** 80 fps instead of 300?

Nope. Try to check if you are limiting your fps using console.
Try fps_max 0

**Comment by jakbes** [comment]
> > is it normal to get **LOCKED** 80 fps instead of 300?
> 
> Nope. Try to check if you are limiting your fps using console.
> Try fps_max 0
i had default 400 but when i set it to 0 it didnt help

**Comment by demitriusdemarcus** [comment]
> > > is it normal to get **LOCKED** 80 fps instead of 300?
> > 
> > 
> > Nope. Try to check if you are limiting your fps using console.
> > Try fps_max 0
> > i had default 400 but when i set it to 0 it didnt help

What features are you using? I tried injecting on both my main PC and my laptop. None seems to have the same problem as yours

**Comment by jakbes** [comment]
I had hand glow that was the issue
